export const articles = [
	{
		link: 'produkcja-kosza',
		img: '/blog1.PNG',
		alt: 'wyplatanie kosza',
		day: '01',
		month: 'KWI',
		title: 'Produkcja kosza wiklinowego',
		text1: `Wyplatanie koszy z wikliny to tradycyjne rzemiosło, które jest
        praktykowane na całym świecie od wieków. Proces ten wymaga dużo
        cierpliwości, precyzji i umiejętności manualnych ...`,
		text2: [
			'Wyplatanie koszy z wikliny to tradycyjne rzemiosło, które jest praktykowane na całym świecie od wieków. Proces ten wymaga dużo cierpliwości, precyzji i umiejętności manualnych, ale końcowy efekt jest niezwykle satysfakcjonujący i piękny',
			' Pierwszym krokiem w procesie wyplatania koszy jest wybranie odpowiedniego gatunku wikliny. Najczęściej wykorzystywane są wiklina wiciowa i wiklina krucha, które charakteryzują się giętkimi pędami i łatwością w wyplataniu. Rośliny te są zbierane wiosną lub latem, gdy ich pędy są najbardziej elastyczne.',
			' Następnie pędy są poddawane procesowi suszenia, aby pozbyć się nadmiaru wilgoci i uodpornić je na uszkodzenia. Po wysuszeniu, pędy są podzielenie na cienkie paski, które będą służyć do wyplatania kosza.',
			'Proces wyplatania koszy zaczyna się od wytworzenia podstawy kosza. Na początku, w zależności od wielkości kosza, wyplatane są jedna lub kilka podstawowych warstw, które mają na celu utworzenie podstawy o odpowiedniej wielkości i kształcie.',
			' Kolejnym etapem jest wyplatanie boków kosza. Paski wikliny są zazwyczaj nawijane na specjalnej formie, aby ułatwić proces wyplatania. Wyplatane są kolejno paski wzdłuż całego kosza, aż do uzyskania pożądanej wysokości.',
			'Ostatnim etapem jest wykończenie górnej krawędzi kosza. Często dodaje się do niej specjalną obręcz, która ma na celu wzmocnienie struktury kosza i nadanie mu estetycznego wyglądu. Obręcz jest najczęściej wykonana z drewna lub metalu, ale można ją również wykonać z wikliny.',
			' Wyplatane kosze z wikliny mają wiele zastosowań. Są one często wykorzystywane w przemyśle spożywczym do przechowywania owoców i warzyw, ale również w przemyśle dekoracyjnym jako elementy wystroju wnętrz, a także jako biżuteria i ozdoby.',
			'   Podsumowując, proces wyplatania koszy z wikliny jest tradycyjnym rzemiosłem, które wymaga dużo cierpliwości i umiejętności. Kosze wyplatane z wikliny są piękne i praktyczne, a ich produkcja jest związana z długą historią i tradycją.',
		],
	},
	{
		link: 'materiał-wiklina',
		img: '/blog2.PNG',
		alt: 'ścięta wiklina',
		day: '17',
		month: 'MAR',
		title: 'Piękno i funkcjonalność naturalnej wikliny',
		text1: `Materiał, który jest wykorzystywany do produkcji koszy wiklinowych, to oczywiście wiklina. Jest to rodzaj rośliny z rodziny wierzbowatych, charakteryzującej się giętkimi i elastycznymi pędami...`,
		text2: [
			'Materiał, który jest wykorzystywany do produkcji koszy wiklinowych, to oczywiście wiklina. Jest to rodzaj rośliny z rodziny wierzbowatych, charakteryzującej się giętkimi i elastycznymi pędami, które idealnie nadają się do wyplatania różnego rodzaju przedmiotów, w tym koszy.',
			'Historia wykorzystywania wikliny do wyplatania koszy sięga tysięcy lat wstecz i związana jest z praktykami ludów pierwotnych, które wykorzystywały kosze do transportu, przechowywania i przenoszenia żywności oraz innych przedmiotów. Dzisiaj kosze wiklinowe są cenione ze względu na swoją funkcjonalność i estetykę, a także z powodu ekologicznego i naturalnego charakteru materiału.',
			' Wiklina, która jest wykorzystywana do wyplatania koszy, pochodzi z wielu różnych gatunków roślin. Najczęściej wykorzystywane są wiklina wiciowa i wiklina krucha, ale można także spotkać kosze wykonane z innych gatunków wikliny, takich jak wiklina czerwona, wiklina siwa czy wiklina morska. Każdy gatunek wikliny ma swoje specyficzne cechy, które wpływają na proces wyplatania koszy oraz na ich trwałość i wytrzymałość.',
			'Wiklina jest surowcem, który charakteryzuje się dużą elastycznością i odpornością na uszkodzenia. Po zebraniu, pędy są suszone, a następnie dzielone na cienkie paski, które będą służyć do wyplatania koszy. Kolor wikliny może być naturalny, brązowy lub zielony, ale można ją także farbować na różne kolory, w zależności od potrzeb.',
			'Proces wyplatania koszy z wikliny wymaga dużo cierpliwości, precyzji i umiejętności manualnych. Wyplatanie koszy zaczyna się od wytworzenia podstawy kosza, a następnie wyplatane są kolejno boki kosza, aż do uzyskania pożądanej wysokości. Ostatnim etapem jest wykończenie górnej krawędzi kosza, często poprzez dodanie specjalnej obręczy, która wzmocni strukturę kosza i nadaje mu estetycznego wyglądu.',
			'Kosze wiklinowe mają wiele zastosowań, zarówno w codziennym użytku, jak i w przemyśle dekoracyjnym. Mogą być używane do przechowywania owoców i warzyw, do transportu i przenoszenia różnych przedmiotów, a także jako elementy wystroju wnętrz. Kosze wiklinowe są bardzo trwałe i wytrzymałe, co czyni je idealnymi do użytku codziennego.',
		],
	},
	{
		link: 'nietypowe-wyroby',
		img: '/blog3.PNG',
		alt: 'biżuteria z wikliny',
		day: '12',
		month: 'LUT',
		title: 'Nietypowe wyroby z wikliny',
		text1: `Materiał, który jest wykorzystywany do produkcji koszy wiklinowych, to oczywiście wiklina. Jest to rodzaj rośliny z rodziny wierzbowatych, charakteryzującej się giętkimi i elastycznymi pędami...`,
		text2: [
			'Wiklina to materiał, który od tysięcy lat jest wykorzystywany do wyplatania różnego rodzaju przedmiotów. Zazwyczaj kojarzy się ona przede wszystkim z koszami, ale w rzeczywistości z wikliny można wykonać wiele innych ciekawych i nietypowych wyrobów. W tym artykule przedstawimy kilka nietypowych wyrobów z wikliny i opowiemy o ich zastosowaniach.',
			'Biżuteria z wikliny to ciekawy i oryginalny pomysł na dodatek do letnich stylizacji. Może być wykonana z cienkich pasków wikliny, które są splatane w różne wzory i formy, a następnie wykończone zawieszkami, klipsami czy zapięciami. Biżuteria z wikliny może mieć różne kolory i odcienie, dzięki czemu łatwo dopasować ją do swojego stylu.',
			' Lampy wiklinowe to eleganckie i stylowe oświetlenie, które świetnie sprawdza się w rustykalnych i naturalnych wnętrzach. Lampy wykonane są z wikliny, która jest ręcznie wyplatana w różne wzory i formy. Mogą mieć różne kształty i rozmiary, od małych kinkietów po duże wiszące lampy.',
			'Meble z wikliny to doskonały wybór dla osób ceniących sobie naturalne i ekologiczne materiały. Krzesła, fotele czy stoły wykonane z wikliny są nie tylko piękne, ale także bardzo wygodne i funkcjonalne. Meble z wikliny świetnie sprawdzają się w letnich ogródkach i na tarasach, ale także w pomieszczeniach mieszkalnych.',
			'Torby i plecaki z wikliny to idealny wybór dla osób ceniących sobie wygodę i styl. Torby z wikliny są bardzo pojemne i wytrzymałe, dzięki czemu doskonale sprawdzą się na zakupy czy do noszenia dokumentów i laptopa. Mogą mieć różne kształty i rozmiary, a także dodatki wykonane z naturalnej skóry lub tkaniny.',
			' Biurka i akcesoria biurowe z wikliny to doskonały wybór dla osób, które cenią sobie prostotę i naturalność. Biurka z wikliny są bardzo wytrzymałe i trwałe, a także bardzo estetyczne. Akcesoria biurowe, takie jak koszyki na dokumenty czy uchwyty na długopisy, wykonane z wikliny, nadają pomieszczeniu biurowemu naturalnego i przyjemnego wyglądu.',
		],
	},
];
